name: fyp_two
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  tflite_flutter: ^0.10.4
  image : ^4.5.2
  image_picker: ^0.8.6
  path_provider: ^2.0.3
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.4.2
  velocity_x: ^4.2.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  permission_handler: ^11.3.1
  get: ^4.6.6
  font_awesome_flutter: ^10.0.0
  sms_autofill: ^2.0.0
  google_api_availability: ^5.0.0
  firebase_storage: ^12.3.7
  #camera: ^0.9.4+1
  #  tflite: ^1.1.2
  table_calendar: ^3.1.2
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  #  flutter_timezone: ^4.0.0
  firebase_messaging: ^15.1.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  cloud_functions: ^5.2.0
  dart_firebase_functions: ^0.0.1-dev.1
  cached_network_image: ^3.3.0  # or the latest version
  file_picker: ^8.1.6
  geolocator: ^13.0.2
  http: ^1.0.0
  provider: ^6.1.1
  flutter_stripe: ^11.5.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/cats_dogs_model.tflite

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript/DancingScript-Bold.ttf
  #
